//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailingWebservice
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeOfMail", Namespace="http://schemas.datacontract.org/2004/07/MailingWebService")]
    public enum TypeOfMail : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTML = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailingWebservice.IMailingWebService")]
    public interface IMailingWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWithSimpleFileWValidity", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWithSimpleFileWValidityResponse")]
        MailingWebservice.SendEmailWithSimpleFileWValidityResponse SendEmailWithSimpleFileWValidity(MailingWebservice.SendEmailWithSimpleFileWValidityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWithSimpleFileWValidity", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWithSimpleFileWValidityResponse")]
        System.Threading.Tasks.Task<MailingWebservice.SendEmailWithSimpleFileWValidityResponse> SendEmailWithSimpleFileWValidityAsync(MailingWebservice.SendEmailWithSimpleFileWValidityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWValidity", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWValidityResponse")]
        MailingWebservice.SendEmailWValidityResponse SendEmailWValidity(MailingWebservice.SendEmailWValidityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWValidity", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWValidityResponse")]
        System.Threading.Tasks.Task<MailingWebservice.SendEmailWValidityResponse> SendEmailWValidityAsync(MailingWebservice.SendEmailWValidityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWithSimpleFile", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWithSimpleFileResponse")]
        MailingWebservice.SendEmailWithSimpleFileResponse SendEmailWithSimpleFile(MailingWebservice.SendEmailWithSimpleFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWithSimpleFile", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWithSimpleFileResponse")]
        System.Threading.Tasks.Task<MailingWebservice.SendEmailWithSimpleFileResponse> SendEmailWithSimpleFileAsync(MailingWebservice.SendEmailWithSimpleFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmail", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailResponse")]
        MailingWebservice.SendEmailResponse SendEmail(MailingWebservice.SendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmail", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailResponse")]
        System.Threading.Tasks.Task<MailingWebservice.SendEmailResponse> SendEmailAsync(MailingWebservice.SendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWithMultipleFiles", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWithMultipleFilesResponse")]
        MailingWebservice.SendEmailWithMultipleFilesResponse SendEmailWithMultipleFiles(MailingWebservice.SendEmailWithMultipleFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWithMultipleFiles", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWithMultipleFilesResponse")]
        System.Threading.Tasks.Task<MailingWebservice.SendEmailWithMultipleFilesResponse> SendEmailWithMultipleFilesAsync(MailingWebservice.SendEmailWithMultipleFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWithMultipleFilesWValidity", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWithMultipleFilesWValidityResponse" +
            "")]
        MailingWebservice.SendEmailWithMultipleFilesWValidityResponse SendEmailWithMultipleFilesWValidity(MailingWebservice.SendEmailWithMultipleFilesWValidityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingWebService/SendEmailWithMultipleFilesWValidity", ReplyAction="http://tempuri.org/IMailingWebService/SendEmailWithMultipleFilesWValidityResponse" +
            "")]
        System.Threading.Tasks.Task<MailingWebservice.SendEmailWithMultipleFilesWValidityResponse> SendEmailWithMultipleFilesWValidityAsync(MailingWebservice.SendEmailWithMultipleFilesWValidityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithSimpleFileWValidity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithSimpleFileWValidityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string To;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string BodyMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public MailingWebservice.TypeOfMail Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int DaysValidity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strFilePath;
        
        public SendEmailWithSimpleFileWValidityRequest()
        {
        }
        
        public SendEmailWithSimpleFileWValidityRequest(string Application, string To, string CC, string Subject, string BodyMessage, MailingWebservice.TypeOfMail Type, int DaysValidity, string strFilePath)
        {
            this.Application = Application;
            this.To = To;
            this.CC = CC;
            this.Subject = Subject;
            this.BodyMessage = BodyMessage;
            this.Type = Type;
            this.DaysValidity = DaysValidity;
            this.strFilePath = strFilePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithSimpleFileWValidityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithSimpleFileWValidityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendEmailWithSimpleFileWValidityResult;
        
        public SendEmailWithSimpleFileWValidityResponse()
        {
        }
        
        public SendEmailWithSimpleFileWValidityResponse(string SendEmailWithSimpleFileWValidityResult)
        {
            this.SendEmailWithSimpleFileWValidityResult = SendEmailWithSimpleFileWValidityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWValidity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWValidityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string To;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string BodyMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public MailingWebservice.TypeOfMail Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int DaysValidity;
        
        public SendEmailWValidityRequest()
        {
        }
        
        public SendEmailWValidityRequest(string Application, string To, string CC, string Subject, string BodyMessage, MailingWebservice.TypeOfMail Type, int DaysValidity)
        {
            this.Application = Application;
            this.To = To;
            this.CC = CC;
            this.Subject = Subject;
            this.BodyMessage = BodyMessage;
            this.Type = Type;
            this.DaysValidity = DaysValidity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWValidityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWValidityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendEmailWValidityResult;
        
        public SendEmailWValidityResponse()
        {
        }
        
        public SendEmailWValidityResponse(string SendEmailWValidityResult)
        {
            this.SendEmailWValidityResult = SendEmailWValidityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithSimpleFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithSimpleFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string To;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string BodyMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public MailingWebservice.TypeOfMail Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strFilePath;
        
        public SendEmailWithSimpleFileRequest()
        {
        }
        
        public SendEmailWithSimpleFileRequest(string Application, string To, string CC, string Subject, string BodyMessage, MailingWebservice.TypeOfMail Type, string strFilePath)
        {
            this.Application = Application;
            this.To = To;
            this.CC = CC;
            this.Subject = Subject;
            this.BodyMessage = BodyMessage;
            this.Type = Type;
            this.strFilePath = strFilePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithSimpleFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithSimpleFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendEmailWithSimpleFileResult;
        
        public SendEmailWithSimpleFileResponse()
        {
        }
        
        public SendEmailWithSimpleFileResponse(string SendEmailWithSimpleFileResult)
        {
            this.SendEmailWithSimpleFileResult = SendEmailWithSimpleFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string To;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string BodyMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public MailingWebservice.TypeOfMail Type;
        
        public SendEmailRequest()
        {
        }
        
        public SendEmailRequest(string Application, string To, string CC, string Subject, string BodyMessage, MailingWebservice.TypeOfMail Type)
        {
            this.Application = Application;
            this.To = To;
            this.CC = CC;
            this.Subject = Subject;
            this.BodyMessage = BodyMessage;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendEmailResult;
        
        public SendEmailResponse()
        {
        }
        
        public SendEmailResponse(string SendEmailResult)
        {
            this.SendEmailResult = SendEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithMultipleFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithMultipleFilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string To;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string BodyMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public MailingWebservice.TypeOfMail Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int DaysValidity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string[] strFilePaths;
        
        public SendEmailWithMultipleFilesRequest()
        {
        }
        
        public SendEmailWithMultipleFilesRequest(string Application, string To, string CC, string Subject, string BodyMessage, MailingWebservice.TypeOfMail Type, int DaysValidity, string[] strFilePaths)
        {
            this.Application = Application;
            this.To = To;
            this.CC = CC;
            this.Subject = Subject;
            this.BodyMessage = BodyMessage;
            this.Type = Type;
            this.DaysValidity = DaysValidity;
            this.strFilePaths = strFilePaths;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithMultipleFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithMultipleFilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendEmailWithMultipleFilesResult;
        
        public SendEmailWithMultipleFilesResponse()
        {
        }
        
        public SendEmailWithMultipleFilesResponse(string SendEmailWithMultipleFilesResult)
        {
            this.SendEmailWithMultipleFilesResult = SendEmailWithMultipleFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithMultipleFilesWValidity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithMultipleFilesWValidityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string To;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string BodyMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public MailingWebservice.TypeOfMail Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int DaysValidity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string[] strFilePaths;
        
        public SendEmailWithMultipleFilesWValidityRequest()
        {
        }
        
        public SendEmailWithMultipleFilesWValidityRequest(string Application, string To, string CC, string Subject, string BodyMessage, MailingWebservice.TypeOfMail Type, int DaysValidity, string[] strFilePaths)
        {
            this.Application = Application;
            this.To = To;
            this.CC = CC;
            this.Subject = Subject;
            this.BodyMessage = BodyMessage;
            this.Type = Type;
            this.DaysValidity = DaysValidity;
            this.strFilePaths = strFilePaths;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithMultipleFilesWValidityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithMultipleFilesWValidityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendEmailWithMultipleFilesWValidityResult;
        
        public SendEmailWithMultipleFilesWValidityResponse()
        {
        }
        
        public SendEmailWithMultipleFilesWValidityResponse(string SendEmailWithMultipleFilesWValidityResult)
        {
            this.SendEmailWithMultipleFilesWValidityResult = SendEmailWithMultipleFilesWValidityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IMailingWebServiceChannel : MailingWebservice.IMailingWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class MailingWebServiceClient : System.ServiceModel.ClientBase<MailingWebservice.IMailingWebService>, MailingWebservice.IMailingWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MailingWebServiceClient() : 
                base(MailingWebServiceClient.GetDefaultBinding(), MailingWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMailingWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailingWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MailingWebServiceClient.GetBindingForEndpoint(endpointConfiguration), MailingWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailingWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MailingWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailingWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MailingWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailingWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public MailingWebservice.SendEmailWithSimpleFileWValidityResponse SendEmailWithSimpleFileWValidity(MailingWebservice.SendEmailWithSimpleFileWValidityRequest request)
        {
            return base.Channel.SendEmailWithSimpleFileWValidity(request);
        }
        
        public System.Threading.Tasks.Task<MailingWebservice.SendEmailWithSimpleFileWValidityResponse> SendEmailWithSimpleFileWValidityAsync(MailingWebservice.SendEmailWithSimpleFileWValidityRequest request)
        {
            return base.Channel.SendEmailWithSimpleFileWValidityAsync(request);
        }
        
        public MailingWebservice.SendEmailWValidityResponse SendEmailWValidity(MailingWebservice.SendEmailWValidityRequest request)
        {
            return base.Channel.SendEmailWValidity(request);
        }
        
        public System.Threading.Tasks.Task<MailingWebservice.SendEmailWValidityResponse> SendEmailWValidityAsync(MailingWebservice.SendEmailWValidityRequest request)
        {
            return base.Channel.SendEmailWValidityAsync(request);
        }
        
        public MailingWebservice.SendEmailWithSimpleFileResponse SendEmailWithSimpleFile(MailingWebservice.SendEmailWithSimpleFileRequest request)
        {
            return base.Channel.SendEmailWithSimpleFile(request);
        }
        
        public System.Threading.Tasks.Task<MailingWebservice.SendEmailWithSimpleFileResponse> SendEmailWithSimpleFileAsync(MailingWebservice.SendEmailWithSimpleFileRequest request)
        {
            return base.Channel.SendEmailWithSimpleFileAsync(request);
        }
        
        public MailingWebservice.SendEmailResponse SendEmail(MailingWebservice.SendEmailRequest request)
        {
            return base.Channel.SendEmail(request);
        }
        
        public System.Threading.Tasks.Task<MailingWebservice.SendEmailResponse> SendEmailAsync(MailingWebservice.SendEmailRequest request)
        {
            return base.Channel.SendEmailAsync(request);
        }
        
        public MailingWebservice.SendEmailWithMultipleFilesResponse SendEmailWithMultipleFiles(MailingWebservice.SendEmailWithMultipleFilesRequest request)
        {
            return base.Channel.SendEmailWithMultipleFiles(request);
        }
        
        public System.Threading.Tasks.Task<MailingWebservice.SendEmailWithMultipleFilesResponse> SendEmailWithMultipleFilesAsync(MailingWebservice.SendEmailWithMultipleFilesRequest request)
        {
            return base.Channel.SendEmailWithMultipleFilesAsync(request);
        }
        
        public MailingWebservice.SendEmailWithMultipleFilesWValidityResponse SendEmailWithMultipleFilesWValidity(MailingWebservice.SendEmailWithMultipleFilesWValidityRequest request)
        {
            return base.Channel.SendEmailWithMultipleFilesWValidity(request);
        }
        
        public System.Threading.Tasks.Task<MailingWebservice.SendEmailWithMultipleFilesWValidityResponse> SendEmailWithMultipleFilesWValidityAsync(MailingWebservice.SendEmailWithMultipleFilesWValidityRequest request)
        {
            return base.Channel.SendEmailWithMultipleFilesWValidityAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMailingWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMailingWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://webapps1.cw01.contiwan.com:8080/MailingWeb/MailingWebService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MailingWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMailingWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MailingWebServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMailingWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMailingWebService,
        }
    }
}
