//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/*
namespace UserAuth
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationType", Namespace="http://schemas.datacontract.org/2004/07/UserAuthenticateSAPLDAP")]
    public enum AuthenticationType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAP = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAPOLD = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UID = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeData", Namespace="http://schemas.datacontract.org/2004/07/UserAuthenticateSAPLDAP")]
    public partial class EmployeeData : object
    {
        
        private string ABKRSField;
        
        private string AdminTimeRecField;
        
        private string AdminTimeRecNumberField;
        
        private string ApplicationProfileField;
        
        private bool AuthenticatedField;
        
        private System.DateTime BirthDayField;
        
        private string CompanyCodeField;
        
        private string CostCenterField;
        
        private System.DateTime CreationDateField;
        
        private string EMailField;
        
        private string EncryptedPasswordField;
        
        private string ErrorMessageField;
        
        private string FacilityField;
        
        private string FirstNameField;
        
        private string FullNameField;
        
        private string GenderField;
        
        private string GroupField;
        
        private string LaborRelationShipField;
        
        private string LastNameField;
        
        private string NumberField;
        
        private string OrganizationalUnitField;
        
        private string OrganizationalUnitNameField;
        
        private string PayrollAreaField;
        
        private string PositionField;
        
        private string PositionNameField;
        
        private string ShiftField;
        
        private string StaffDivisionField;
        
        private string StaffSubDivisionField;
        
        private string StellField;
        
        private string SubGroupField;
        
        private bool TimeManagerField;
        
        private string WindowsUserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ABKRS
        {
            get
            {
                return this.ABKRSField;
            }
            set
            {
                this.ABKRSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminTimeRec
        {
            get
            {
                return this.AdminTimeRecField;
            }
            set
            {
                this.AdminTimeRecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminTimeRecNumber
        {
            get
            {
                return this.AdminTimeRecNumberField;
            }
            set
            {
                this.AdminTimeRecNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationProfile
        {
            get
            {
                return this.ApplicationProfileField;
            }
            set
            {
                this.ApplicationProfileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Authenticated
        {
            get
            {
                return this.AuthenticatedField;
            }
            set
            {
                this.AuthenticatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDay
        {
            get
            {
                return this.BirthDayField;
            }
            set
            {
                this.BirthDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CostCenter
        {
            get
            {
                return this.CostCenterField;
            }
            set
            {
                this.CostCenterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail
        {
            get
            {
                return this.EMailField;
            }
            set
            {
                this.EMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncryptedPassword
        {
            get
            {
                return this.EncryptedPasswordField;
            }
            set
            {
                this.EncryptedPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Facility
        {
            get
            {
                return this.FacilityField;
            }
            set
            {
                this.FacilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LaborRelationShip
        {
            get
            {
                return this.LaborRelationShipField;
            }
            set
            {
                this.LaborRelationShipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationalUnit
        {
            get
            {
                return this.OrganizationalUnitField;
            }
            set
            {
                this.OrganizationalUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationalUnitName
        {
            get
            {
                return this.OrganizationalUnitNameField;
            }
            set
            {
                this.OrganizationalUnitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayrollArea
        {
            get
            {
                return this.PayrollAreaField;
            }
            set
            {
                this.PayrollAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionName
        {
            get
            {
                return this.PositionNameField;
            }
            set
            {
                this.PositionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shift
        {
            get
            {
                return this.ShiftField;
            }
            set
            {
                this.ShiftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffDivision
        {
            get
            {
                return this.StaffDivisionField;
            }
            set
            {
                this.StaffDivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffSubDivision
        {
            get
            {
                return this.StaffSubDivisionField;
            }
            set
            {
                this.StaffSubDivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stell
        {
            get
            {
                return this.StellField;
            }
            set
            {
                this.StellField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubGroup
        {
            get
            {
                return this.SubGroupField;
            }
            set
            {
                this.SubGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TimeManager
        {
            get
            {
                return this.TimeManagerField;
            }
            set
            {
                this.TimeManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WindowsUserId
        {
            get
            {
                return this.WindowsUserIdField;
            }
            set
            {
                this.WindowsUserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserAuth.IUserAuthenticate")]
    public interface IUserAuthenticate
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticate/UserAuthenticationApplication", ReplyAction="http://tempuri.org/IUserAuthenticate/UserAuthenticationApplicationResponse")]
        System.Threading.Tasks.Task<UserAuth.EmployeeData> UserAuthenticationApplicationAsync(UserAuth.AuthenticationType AuthenticationType, string UserId, string Password, string Domain, string ApplicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticate/UserAuthentication", ReplyAction="http://tempuri.org/IUserAuthenticate/UserAuthenticationResponse")]
        System.Threading.Tasks.Task<UserAuth.EmployeeData> UserAuthenticationAsync(UserAuth.AuthenticationType AuthenticationType, string UserId, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticate/EmployeeMainData", ReplyAction="http://tempuri.org/IUserAuthenticate/EmployeeMainDataResponse")]
        System.Threading.Tasks.Task<UserAuth.EmployeeData> EmployeeMainDataAsync(string EmployeeNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IUserAuthenticateChannel : UserAuth.IUserAuthenticate, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class UserAuthenticateClient : System.ServiceModel.ClientBase<UserAuth.IUserAuthenticate>, UserAuth.IUserAuthenticate
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserAuthenticateClient() : 
                base(UserAuthenticateClient.GetDefaultBinding(), UserAuthenticateClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUserAuthenticate.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserAuthenticateClient(EndpointConfiguration endpointConfiguration) : 
                base(UserAuthenticateClient.GetBindingForEndpoint(endpointConfiguration), UserAuthenticateClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserAuthenticateClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserAuthenticateClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserAuthenticateClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserAuthenticateClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserAuthenticateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<UserAuth.EmployeeData> UserAuthenticationApplicationAsync(UserAuth.AuthenticationType AuthenticationType, string UserId, string Password, string Domain, string ApplicationId)
        {
            return base.Channel.UserAuthenticationApplicationAsync(AuthenticationType, UserId, Password, Domain, ApplicationId);
        }
        
        public System.Threading.Tasks.Task<UserAuth.EmployeeData> UserAuthenticationAsync(UserAuth.AuthenticationType AuthenticationType, string UserId, string Password)
        {
            return base.Channel.UserAuthenticationAsync(AuthenticationType, UserId, Password);
        }
        
        public System.Threading.Tasks.Task<UserAuth.EmployeeData> EmployeeMainDataAsync(string EmployeeNumber)
        {
            return base.Channel.EmployeeMainDataAsync(EmployeeNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserAuthenticate))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserAuthenticate))
            {
                return new System.ServiceModel.EndpointAddress("http://webapps3.cw01.contiwan.com:8080/UserAuthenticateSAPLDAP/UserAuthenticate.s" +
                        "vc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserAuthenticateClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUserAuthenticate);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserAuthenticateClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUserAuthenticate);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUserAuthenticate,
        }
    }
}
*/